location ~ ^/(config\.php|nginx\.example\.conf|nginx\.rewrite\.conf|bt\.rewrite\.conf|storage/) {
    deny all;
}

location = / {
    rewrite ^ /index.php last;
}

location / {
    try_files $uri /index.php?$query_string;
}